# fly.toml app configuration file
app = "customs-api" #
primary_region = "ams" # Amsterdam (Good latency for Greece)

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb" # Keeps it within free tier limits if applicable

# UNCOMMENT THE SECTION BELOW IF YOU WANT YOUR DATABASE TO SURVIVE RESTARTS
# You must run: fly volumes create data_vol -a your-app-name-here
# [mounts]
#   source = "data_vol"
#   destination = "/data"